TARGET_BOARD_PLATFORM := msmnile
TARGET_BOARD_PLATFORM_GPU := qcom-adreno640

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := kryo300

TARGET_CPU_ABI2 := armeabi-v7a
TARGET_CPU_VARIANT_RUNTIME := kryo300

TARGET_USES_64_BIT_BINDER := true
TARGET_BOOTLOADER_BOARD_NAME := raphael
TARGET_NO_BOOTLOADER := true
TARGET_SUPPORTS_64_BIT_APPS := true

BOARD_VENDOR := xiaomi
BOARD_KERNEL_CMDLINE := console=ttyMSM0,115200n8
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64

